# Generated by Django 3.0.5 on 2020-04-10 09:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='review_content',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_number',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3),
        ),
    ]
